#!/usr/bin/env python3
"""
Seed Go Stay & Board sub-category products (21 products)
GO-BC-001 to GO-SS-003
"""
import os, sys, uuid
sys.path.insert(0, '/app/backend')
from dotenv import load_dotenv
load_dotenv('/app/backend/.env')
from pymongo import MongoClient

client = MongoClient(os.environ['MONGO_URL'])
db = client[os.environ.get('DB_NAME', 'pet_life_os')]

STAY_PRODUCTS = [
    # boarding_comfort
    {"id": "GO-BC-001", "name": "Familiar Scent Blanket", "pillar": "go", "category": "stay", "sub_category": "boarding_comfort", "dimension": "Stay & Board", "description": "Soft blanket with home scent to comfort your dog during boarding — reduces anxiety in new environments", "price": 799, "mira_tag": "Boarding Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a soft cream-coloured fleece blanket folded neatly with a small paw print tag, warm cosy tones, white background"},
    {"id": "GO-BC-002", "name": "Boarding Comfort Toy Set", "pillar": "go", "category": "stay", "sub_category": "boarding_comfort", "dimension": "Stay & Board", "description": "Set of 3 familiar-scent toys — keep your dog occupied and calm in a new boarding environment", "price": 699, "mira_tag": "Boarding Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a set of 3 soft comfort toys in cream and sage tones, minimal, white background"},
    {"id": "GO-BC-003", "name": "Boarding Food Container Kit", "pillar": "go", "category": "stay", "sub_category": "boarding_comfort", "dimension": "Stay & Board", "description": "Labelled, airtight containers for pre-portioned meals — boarding staff know exactly what to feed", "price": 549, "mira_tag": "Boarding Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a set of 3 labelled airtight food containers in teal and cream, clean and minimal, white background"},
    {"id": "GO-BC-004", "name": "Medication Organiser for Boarding", "pillar": "go", "category": "stay", "sub_category": "boarding_comfort", "dimension": "Stay & Board", "description": "Labelled daily pill organiser with care instructions — essential for dogs on medication during boarding", "price": 399, "mira_tag": "Boarding Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a small 7-day pill organiser with Mon-Sun labels, clean teal and white design, white background"},
    # daycare_essentials
    {"id": "GO-DC-001", "name": "Daycare Bag — Personalised", "pillar": "go", "category": "stay", "sub_category": "daycare_essentials", "dimension": "Stay & Board", "description": "Canvas tote with your dog's name — holds food, treats, collar change, and daycare essentials", "price": 899, "mira_tag": "Daycare Essential", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a personalised canvas tote bag with embroidered dog name, teal handle, white background"},
    {"id": "GO-DC-002", "name": "Daycare ID Tag + QR Code", "pillar": "go", "category": "stay", "sub_category": "daycare_essentials", "dimension": "Stay & Board", "description": "Engraved metal tag with QR code linking to your dog's profile — daycare staff can scan for full care instructions", "price": 499, "mira_tag": "Daycare Essential", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a small round engraved metal tag with QR code, gold finish, white background"},
    {"id": "GO-DC-003", "name": "Training Treats — Daycare Pack", "pillar": "go", "category": "stay", "sub_category": "daycare_essentials", "dimension": "Stay & Board", "description": "High-value training treats for daycare socialisation — chicken-free, allergy-aware options available", "price": 349, "mira_tag": "Daycare Essential", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a neat pack of small training treats with Daycare Pack label, teal and cream packaging, white background"},
    # pet_sitting_kit
    {"id": "GO-PS-001", "name": "Pet Sitter Info Card Set", "pillar": "go", "category": "stay", "sub_category": "pet_sitting_kit", "dimension": "Stay & Board", "description": "Laminated A5 cards: feeding schedule, vet contact, emergency numbers, medication — everything a sitter needs at a glance", "price": 299, "mira_tag": "Pet Sitting", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a set of laminated A5 care instruction cards with paw print design, teal and cream, white background"},
    {"id": "GO-PS-002", "name": "Sitter Welcome Pack", "pillar": "go", "category": "stay", "sub_category": "pet_sitting_kit", "dimension": "Stay & Board", "description": "Complete kit: info card, 3-day food portions, treat bag, poop bags, and emergency contact card", "price": 1299, "mira_tag": "Pet Sitting", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a neat sitter welcome kit with food portions, care card, and treat bag in a teal pouch, white background"},
    {"id": "GO-PS-003", "name": "Home Key Tag + QR Code", "pillar": "go", "category": "stay", "sub_category": "pet_sitting_kit", "dimension": "Stay & Board", "description": "Smart key tag with QR code linking to home access instructions and emergency contacts — for sitters with home access", "price": 399, "mira_tag": "Pet Sitting", "is_mira_pick": False, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a small smart key tag with QR code and Home Access label, minimal black and teal design, white background"},
    # hotel_comfort
    {"id": "GO-HT-001", "name": "Portable Luxury Pet Bed", "pillar": "go", "category": "stay", "sub_category": "hotel_comfort", "dimension": "Stay & Board", "description": "Compact roll-up orthopaedic travel bed — fits in cabin luggage, sets up in any hotel room in seconds", "price": 1899, "mira_tag": "Hotel Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a rolled portable pet bed in sage green with carry strap, luxurious but compact, white background"},
    {"id": "GO-HT-002", "name": "Hotel Room Pet Kit", "pillar": "go", "category": "stay", "sub_category": "hotel_comfort", "dimension": "Stay & Board", "description": "Waterproof mat, collapsible bowl, poop bags, and pet-safe room spray — everything for a clean hotel stay", "price": 1299, "mira_tag": "Hotel Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a hotel pet kit in a neat teal pouch, mat bowls bags visible, white background"},
    {"id": "GO-HT-003", "name": "Pet-Safe Room Spray", "pillar": "go", "category": "stay", "sub_category": "hotel_comfort", "dimension": "Stay & Board", "description": "Calming lavender and chamomile room spray — safe for dogs, masks unfamiliar hotel room scents", "price": 599, "mira_tag": "Hotel Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a small elegant spray bottle labelled Pet-Safe Room Calm, sage green and cream, white background"},
    {"id": "GO-HT-004", "name": "Waterproof Hotel Floor Mat", "pillar": "go", "category": "stay", "sub_category": "hotel_comfort", "dimension": "Stay & Board", "description": "Thick waterproof mat protects hotel carpet and gives your dog a defined clean space — rolls up easily", "price": 799, "mira_tag": "Hotel Comfort", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a rolled waterproof pet floor mat in teal with non-slip base, minimal, white background"},
    # first_stay_anxiety
    {"id": "GO-FA-001", "name": "First Stay Calming Kit", "pillar": "go", "category": "stay", "sub_category": "first_stay_anxiety", "dimension": "Stay & Board", "description": "Complete calming system for dogs entering boarding or a hotel for the first time — spray, chews, and blanket", "price": 1499, "mira_tag": "Anxiety Relief", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a first stay calming kit with spray, chews, and soft blanket in a gift box, teal and cream, white background"},
    {"id": "GO-FA-002", "name": "Anxiety Wrap / Thunder Shirt", "pillar": "go", "category": "stay", "sub_category": "first_stay_anxiety", "dimension": "Stay & Board", "description": "Pressure wrap that reduces anxiety in new environments — scientifically proven, sized for all breeds", "price": 1899, "mira_tag": "Anxiety Relief", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a soft anxiety wrap thunder shirt for dogs in grey and teal, clean minimal photo, white background"},
    {"id": "GO-FA-003", "name": "Pheromone Calming Collar", "pillar": "go", "category": "stay", "sub_category": "first_stay_anxiety", "dimension": "Stay & Board", "description": "Releases calming pheromones for up to 30 days — perfect for extended boarding or a multi-night hotel stay", "price": 899, "mira_tag": "Anxiety Relief", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a calming pheromone collar in neutral tan, clean minimal product photo, white background"},
    {"id": "GO-FA-004", "name": "Night Light for Boarding", "pillar": "go", "category": "stay", "sub_category": "first_stay_anxiety", "dimension": "Stay & Board", "description": "Small battery-powered night light — comfort for dogs anxious in dark, unfamiliar boarding rooms", "price": 499, "mira_tag": "Anxiety Relief", "is_mira_pick": False, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a small soft-glow night light with paw print design, warm amber light, white background"},
    # soul_stay
    {"id": "GO-SS-001", "name": "Breed Travel Bandana — Stay Edition", "pillar": "go", "category": "stay", "sub_category": "soul_stay", "dimension": "Stay & Board", "description": "Personalised bandana with breed name and 'Staying at...' — identifies your dog at boarding or daycare", "price": 399, "mira_tag": "Soul Stay", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a folded bandana with Staying at embroidery, teal and cream, white background"},
    {"id": "GO-SS-002", "name": "Personalised Boarding Tag", "pillar": "go", "category": "stay", "sub_category": "soul_stay", "dimension": "Stay & Board", "description": "Engraved metal tag: dog's name, boarding facility name, emergency contact — specific to each stay", "price": 549, "mira_tag": "Soul Stay", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: an engraved metal boarding tag with dog name and facility info, gold finish, white background"},
    {"id": "GO-SS-003", "name": "Gotcha Day Stay Box", "pillar": "go", "category": "stay", "sub_category": "soul_stay", "dimension": "Stay & Board", "description": "If your dog's Gotcha Day falls while you're away — a special delivery to the boarding facility with their favourite things", "price": 1499, "mira_tag": "Soul Stay", "is_mira_pick": True, "status": "active", "image_url": None, "ai_image_prompt": "Realistic product photo: a beautiful gift box labelled Happy Gotcha Day with treats, toy, and bandana inside, rose and cream tones, white background"},
]

inserted = 0
skipped = 0
for p in STAY_PRODUCTS:
    existing = db.products_master.find_one({"id": p["id"]})
    if existing:
        skipped += 1
        print(f"  SKIP (exists): {p['id']}")
    else:
        db.products_master.insert_one(p)
        inserted += 1
        print(f"  ADD: {p['id']} — {p['name']}")

print(f"\nDone: {inserted} inserted, {skipped} skipped")
print(f"Total go products: {db.products_master.count_documents({'pillar': 'go'})}")
