"""
Test Suite for Product Box APIs - Iteration 227
Tests: HUFT products, breed-specific products, admin Product Box UI APIs

Features to test:
1. /api/product-box/products returns products correctly
2. HUFT products search returns 20 products
3. Breed-specific products (search 'shih tzu', 'indie', 'labrador') return personalized items
4. Product stats API returns updated counts (2503+ total)
5. Product filtering by pillar works
6. Product search works
"""

import pytest
import requests
import os

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', 'https://mockup-manager.preview.emergentagent.com')


class TestProductBoxAPIs:
    """Test suite for Product Box APIs"""
    
    def test_products_endpoint_returns_data(self):
        """Test GET /api/product-box/products returns products"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?limit=10")
        assert response.status_code == 200, f"Products endpoint failed: {response.text}"
        
        data = response.json()
        assert "products" in data, "Response should have 'products' field"
        assert "total" in data, "Response should have 'total' field"
        assert len(data["products"]) > 0, "Should return at least one product"
        assert data["total"] >= 2500, f"Expected 2500+ products, got {data['total']}"
        
        # Validate product structure
        product = data["products"][0]
        assert "id" in product, "Product should have 'id' field"
        assert "name" in product, "Product should have 'name' field"
        print(f"✅ Products endpoint returned {data['total']} total products")
    
    def test_huft_products_search_returns_20(self):
        """Test HUFT products search returns exactly 20 products"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=HUFT&limit=25")
        assert response.status_code == 200, f"HUFT search failed: {response.text}"
        
        data = response.json()
        assert data["total"] == 20, f"Expected 20 HUFT products, got {data['total']}"
        
        # Verify all products are HUFT brand
        for product in data["products"]:
            assert "HUFT" in product.get("name", ""), f"Product {product.get('id')} is not a HUFT product"
        
        print(f"✅ HUFT products search returned {data['total']} products")
    
    def test_product_stats_total_count(self):
        """Test product stats API returns 2503+ total products"""
        response = requests.get(f"{BASE_URL}/api/product-box/stats")
        assert response.status_code == 200, f"Stats endpoint failed: {response.text}"
        
        data = response.json()
        assert "total" in data, "Stats should have 'total' field"
        assert data["total"] >= 2503, f"Expected 2503+ total, got {data['total']}"
        
        # Validate stats structure
        assert "by_status" in data, "Stats should have 'by_status'"
        assert "by_pillar" in data, "Stats should have 'by_pillar'"
        assert "mira" in data, "Stats should have 'mira' section"
        
        print(f"✅ Stats returned total: {data['total']}, active: {data['by_status'].get('active', 0)}")
    
    def test_breed_filter_labrador(self):
        """Test breed filter for Labrador returns breed-specific products"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?breed=Labrador&limit=20")
        assert response.status_code == 200, f"Labrador breed filter failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Should return Labrador products"
        print(f"✅ Labrador breed filter returned {data['total']} products")
    
    def test_breed_filter_shih_tzu(self):
        """Test breed filter for Shih Tzu returns breed-specific products"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?breed=Shih%20Tzu&limit=20")
        assert response.status_code == 200, f"Shih Tzu breed filter failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Should return Shih Tzu products"
        print(f"✅ Shih Tzu breed filter returned {data['total']} products")
    
    def test_breed_filter_indie(self):
        """Test breed filter for Indie returns breed-specific products"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?breed=Indie&limit=20")
        assert response.status_code == 200, f"Indie breed filter failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Should return Indie products"
        print(f"✅ Indie breed filter returned {data['total']} products")
    
    def test_search_breed_specific_products(self):
        """Test searching for breed-specific personalized products"""
        # Search for Labrador Pawfect Bandana (should be generated by breed generator)
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Labrador%20Pawfect&limit=10")
        assert response.status_code == 200, f"Breed-specific search failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Should find Labrador Pawfect products"
        
        # Verify breed_metadata has correct breed
        found_breed_specific = False
        for product in data["products"]:
            breed_metadata = product.get("breed_metadata", {})
            if breed_metadata.get("breed_specific") and "Labrador" in breed_metadata.get("breeds", []):
                found_breed_specific = True
                break
        
        assert found_breed_specific, "Should find breed-specific Labrador product with correct breed_metadata"
        print(f"✅ Found breed-specific Labrador products")
    
    def test_pillar_filter_shop(self):
        """Test pillar filter for 'shop' pillar"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?pillar=shop&limit=10")
        assert response.status_code == 200, f"Shop pillar filter failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 2000, f"Shop pillar should have 2000+ products, got {data['total']}"
        
        # Verify products have shop pillar
        for product in data["products"]:
            pillars = product.get("pillars", [])
            assert "shop" in pillars, f"Product {product.get('id')} should have 'shop' pillar"
        
        print(f"✅ Shop pillar filter returned {data['total']} products")
    
    def test_pillar_filter_celebrate(self):
        """Test pillar filter for 'celebrate' pillar"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?pillar=celebrate&limit=10")
        assert response.status_code == 200, f"Celebrate pillar filter failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Celebrate pillar should have products"
        print(f"✅ Celebrate pillar filter returned {data['total']} products")
    
    def test_general_search(self):
        """Test general product search"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=cake&limit=20")
        assert response.status_code == 200, f"Cake search failed: {response.text}"
        
        data = response.json()
        assert data["total"] > 0, "Should find cake products"
        print(f"✅ General search 'cake' returned {data['total']} products")
    
    def test_product_structure_has_breed_metadata(self):
        """Test that products have breed_metadata field"""
        # Get Labrador Pawfect Bandana specifically
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Labrador%20Pawfect%20Bandana&limit=5")
        assert response.status_code == 200
        
        data = response.json()
        if data["total"] > 0:
            product = data["products"][0]
            assert "breed_metadata" in product, "Product should have breed_metadata field"
            
            breed_meta = product.get("breed_metadata", {})
            if breed_meta.get("breed_specific"):
                assert "breeds" in breed_meta, "breed_metadata should have 'breeds' field"
                assert "Labrador" in breed_meta.get("breeds", []), "Should have Labrador in breeds"
            print(f"✅ Product has correct breed_metadata: {breed_meta}")
        else:
            print("⚠️ No Labrador Pawfect Bandana found to test breed_metadata")


class TestBreedSpecificProducts:
    """Test breed-specific products created by generate_breed_products.py"""
    
    def test_labrador_products_exist(self):
        """Test Labrador themed products exist"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Labrador%20Pawfect&limit=10")
        assert response.status_code == 200
        
        data = response.json()
        assert data["total"] > 0, "Should have Labrador themed products"
        print(f"✅ Found {data['total']} Labrador themed products")
    
    def test_shih_tzu_products_exist(self):
        """Test Shih Tzu themed products exist"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Shih%20Tzu%20Pawfect&limit=10")
        assert response.status_code == 200
        
        data = response.json()
        assert data["total"] > 0, "Should have Shih Tzu themed products"
        print(f"✅ Found {data['total']} Shih Tzu themed products")
    
    def test_indie_products_exist(self):
        """Test Indie themed products exist"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Indie%20Pawfect&limit=10")
        assert response.status_code == 200
        
        data = response.json()
        assert data["total"] > 0, "Should have Indie themed products"
        print(f"✅ Found {data['total']} Indie themed products")
    
    def test_pug_products_exist(self):
        """Test Pug themed products exist"""
        response = requests.get(f"{BASE_URL}/api/product-box/products?search=Pug%20Pawfect&limit=10")
        assert response.status_code == 200
        
        data = response.json()
        assert data["total"] > 0, "Should have Pug themed products"
        print(f"✅ Found {data['total']} Pug themed products")


class TestAdminLogin:
    """Test admin login functionality"""
    
    def test_admin_auth_basic(self):
        """Test admin login with basic auth"""
        import base64
        credentials = base64.b64encode(b'aditya:lola4304').decode('utf-8')
        headers = {'Authorization': f'Basic {credentials}'}
        
        # Try accessing admin protected endpoint
        response = requests.get(f"{BASE_URL}/api/admin/households", headers=headers)
        # Should not return 401 (unauthorized)
        assert response.status_code != 401, "Admin credentials should be valid"
        print(f"✅ Admin auth works, status: {response.status_code}")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
